criticize:
  description: >
    Find the deficiencies and improvement points in the given prompt: {prompt}. 
    Provide a listed analysis of the prompt's deficiencies and suggest ways to improve it.
    Always reason your suggestions and provide context between the deficiencies and the prompt's goal.
    The points should be technical, professional and standard. They always must be 
    broad, generic and belongs to a technical framework about prompt engineering.
  expected_output: >
    A list of deficiencies in the prompt and suggestions to improve it.
    Each point should be reasoned and provide context between the deficiencies and the prompt's goal.
  agent: retainer

find_framework:
  description: >
    Find a prompt engineering technique framework like COSTAR or else to improve the prompt based on the reported deficiencies of it.
    Provide a detailed explanation of the framework and how it can be applied to the prompt.
  expected_output: >
    A description of the prompt engineering technique framework and how it can be applied to the prompt.
  agent: retainer
  dependencies:
    - criticize
  input:
    deficiencies: criticize.output

search_for_alternative_frameworks:
  description: >
    Find at least two alternatives to given the prompt engineering technique framework.
    Provide a brief description of each alternative and how it can be applied to the prompt.
  expected_output: >
    A brief description of each alternative framework and how it can be applied to the prompt.
  agent: web_searcher
  dependencies:
    - find_framework
  input:
    framework: find_framework.output

create_few_shot_examples:
  description: >
    Write professional few shot examples for each of the prompt engineering frameworks.
    Provide two few shot examples that demonstrate and explain the framework's application in general. Don't use the target prompt in the examples. Just use general and perfect examples which are suitable for the prompt engineering framework.
  expected_output: >
    At least two few shot examples for each framework.
  agent: exampler
  dependencies:
    - find_framework
    - search_for_alternative_frameworks
  input:
    framework: find_framework.output
    alternatives: search_for_alternative_frameworks.output

write_final_prompts:
  description: >
    Write a professional and perfect prompt based on the initial basic given prompt using the findings, suggestions and examples.
    Create a perfect prompt for each unique framework given on the initial prompt.
  expected_output: >
    A professional and perfect prompt for each unique framework given on the initial prompt.
  agent: copywriter
  dependencies:
    - criticize
    - find_framework
    - search_for_alternative_frameworks
    - create_few_shot_examples

  input:
    prompt: criticize.input
    framework: find_framework.output
    alternatives: search_for_alternative_frameworks.output
    examples: create_few_shot_examples.output
